baseURL = "https://www.httpsmith.com/"
languageCode = "en-us"
title = "HTTP Smith"
theme = "techdoc"
publishDir = "docs"

[params]
menu_style = "open-menu"
tag_manager_container_id = "GTM-K6GS2N8"

[outputs]
home = ["HTML", "RSS"]
